### ISSUE TITLE
Use toastr

### ISSUE THREAD

**Issue by magmukendi** [WEPO-RDC/wepoHomepage#1]
Use toastr for showing the alert when a form is submitted

**Comment by thisurathenuka** [comment]
Hi @LeGrandMAG, I'll do this. Please assign this to me. Btw, linters are suggesting quite a lot of warnings in the project. Shall I fix them as well or just the notification part is enough ?

**Comment by magmukendi** [comment]
Hello @thisurathenuka, If you can, that would be amazing.

**Comment by thisurathenuka** [comment]
Hello @LeGrandMAG , There's one issue. `toastr` library is not really up-to-date. Last published date was 5 years. Do you mind if I use `react-toastify` to add notifications rather than `toastr `?

Here is a link to checkout the library. https://www.npmjs.com/package/react-toastify
Let me know if you have other ideas
